import type { FilterDefinition } from '../types';

export const FILTER_CATEGORIES = [
  { id: 'animal'    as const, label: '🐾 Dyr' },
  { id: 'makeup'    as const, label: '💄 Makeup' },
  { id: 'character' as const, label: '👻 Karakter' },
  { id: 'distortion' as const, label: '🤪 Forvrængning' },
  { id: 'distortion2' as const, label: '🌀 Forvrængning 2' },
  { id: 'style'     as const, label: '🎨 Stil' },
  { id: 'effect'    as const, label: '✨ Effekt' },
  { id: 'props'     as const, label: '🕶️ Props' },
];

export const FILTERS: FilterDefinition[] = [
  // Animal
  { id:'dog',              label:'Hund',        icon:'🐶', category:'animal',    description:'Hunde-ører, næse og tunge' },
  { id:'dog2',             label:'Hund 2',       icon:'🐕', category:'animal',    description:'3D malet hundeansigt' },
  { id:'bunny',            label:'Kanin',        icon:'🐰', category:'animal',    description:'Lange ører og lyserød næse' },
  { id:'lion',             label:'Løve',         icon:'🦁', category:'animal',    description:'Løveører foroven og næse/mule forankret på næsen' },
  { id:'lion3d',           label:'Løve 3D',      icon:'🦁', category:'animal',    description:'3D løvehoved-maske (fra foto) der bæres over ansigtet' },
  { id:'horse3',           label:'Hest 3D',      icon:'🐴', category:'animal',    description:'3D hestehoved fastgjort til hovedets pose — omslutter hele ansigtet' },
  // Makeup
  { id:'lip_red',          label:'Rød læbe',     icon:'💋', category:'makeup',   description:'Klassisk rød læbestift' },
  { id:'lip_pink',         label:'Pink læbe',    icon:'🌸', category:'makeup',   description:'Blød pink med glans' },
  { id:'lip_rainbow',      label:'Regnbue læbe', icon:'🌈', category:'makeup',   description:'Læbestift der skifter farve gennem hele farvespektret over tid' },
  { id:'iris_color',       label:'Iris-farve',   icon:'👁️', category:'makeup',   description:'Iris skifter farve gennem hele farvespektret over tid' },
  { id:'eyebrows',        label:'Øjenbryn',      icon:'icons/eyelash.svg', category:'makeup',   description:'3D øjenbryn der lægger sig over og erstatter dine egne (sorte)' },
  // Character
  { id:'anon_mask',        label:'Anon Maske',    icon:'🎭', category:'character', description:'3D anonymous-maske' },
  { id:'anonymous_mask',   label:'Anonymous',     icon:'👤', category:'character', description:'3D Anonymous / Guy Fawkes-maske' },
  { id:'batman2',         label:'Batman',       icon:'🦇', category:'character', description:'3D Batman-cowl' },
  { id:'ironman',          label:'Iron Man',      icon:'🤖', category:'character', description:'3D Iron Man-hjelm' },
  { id:'third_eye',       label:'Tredje Øje',   icon:'👁️', category:'character', description:'Mystisk lilla øje åbner sig på panden' },
  { id:'clown',           label:'Klovn',        icon:'🤡', category:'character', description:'Hvidt ansigt, røde kinder, stor rød mund, 3D-næse og krøllet regnbuehår' },
  { id:'disguise',        label:'Forklædning',  icon:'🥸', category:'character', description:'Groucho-forklædning: briller, store øjenbryn, stor næse og overskæg' },
  { id:'wild_man',        label:'Vild Mand',    icon:'🤪', category:'character', description:'Farverig galning med vildt hår — dine egne øjne skinner igennem' },
  { id:'ass_face',        label:'Røv',          icon:'🍑', category:'character', description:'Røv-ansigt lagt over hovedet — dine egne øjne skinner igennem de to øjenhuller' },
  { id:'anubis',          label:'Anubis',        icon:'🐺', category:'character', description:'3D Anubis-hoved (egyptisk sjakalgud) båret som maske' },
  { id:'triceratops',     label:'Triceratops',   icon:'🦕', category:'character', description:'3D Triceratops-hoved båret som maske' },
  // Style
  { id:'neon',             label:'Neon',         icon:'⚡', category:'style',    description:'Farverige kantlinjer på mørk baggrund' },
  { id:'neon_outline',    label:'Neon Kontur',  icon:'🌈', category:'style',    description:'Glødende neon-kontur langs ansigtslandmarks' },
  { id:'neon_dark',       label:'Neon Mørk',    icon:'🌑', category:'style',    description:'Helt sort baggrund med lysende neon-ansigtskontur' },
  { id:'neon_body',       label:'Neon Krop',    icon:'🕺', category:'style',    description:'Helt sort baggrund hvor hele kroppen lyser i neon' },
  { id:'pencil_sketch',   label:'Blyantskitse', icon:'✏️', category:'style',    description:'Hvid baggrund med mørke blyantstreger' },
  { id:'cyberpunk',        label:'Cyberpunk',    icon:'🤖', category:'style',    description:'HUD-ringe, kredsløb og scanning' },
  { id:'cartoon',          label:'Tegneserie',   icon:'🎨', category:'style',    description:'Fed omrids og halvtone-rødme' },
  { id:'noir',             label:'Noir',         icon:'🎞️', category:'style',   description:'Sort/hvid med filmkorn og vignette' },
  { id:'watercolor',       label:'Akvarel',      icon:'🖌️', category:'style',   description:'Bløde pastelfarver' },
  { id:'oil_paint',        label:'Olie-maleri',  icon:'🖼️', category:'style',   description:'Malet penselstrøg og rige farver' },
  // Effect
  { id:'glitch',           label:'Glitch',       icon:'📺', category:'effect',   description:'RGB-kanal split og støj' },
  { id:'kaleidoscope',     label:'Kaleidoskop',  icon:'🔮', category:'effect',   description:'Ansigtet spejles i 4-vejs kaleidoskop-mønster' },
  { id:'thermal',          label:'Termisk',      icon:'🌡️', category:'effect',  description:'Infrarød varmekort-palet' },
  { id:'night_vision',     label:'Nattesyn',     icon:'🌙', category:'effect',   description:'Grøn nattesyn med crosshair' },
  { id:'hologram',         label:'Hologram',     icon:'💠', category:'effect',   description:'Cyan holografisk overlay' },
  { id:'infrared',         label:'Infrared',     icon:'🔴', category:'effect',   description:'Infrarød farvepalet' },
  // Props (3D via Three.js)
  { id:'sunglasses',       label:'Solbriller',   icon:'🕶️', category:'props',    description:'3D solbriller med glas-refleksion' },
  { id:'party_glasses',    label:'Party Briller', icon:'🥳', category:'props',    description:'3D party-briller' },
  { id:'ski_goggles',      label:'Skibriller',    icon:'🥽', category:'props',    description:'3D skibriller med pink stel og spejlglas' },
  { id:'agf_cap',          label:'AGF Kasket',    icon:'🧢', category:'props',    description:'3D AGF-kasket ovenpå hovedet' },
  { id:'agf_cap_logo',     label:'AGF Kasket Logo', icon:'🧢', category:'props',  description:'Hvid kasket med AGF-byvåben på fronten' },
  { id:'agf_fan',          label:'AGF Fan',       icon:'🔴', category:'props',    description:'AGF-logo malet på begge kinder' },
  { id:'man_utd',          label:'AGF/MUFC',      icon:'🔴', category:'props',    description:'AGF-logo til venstre og Manchester United til højre — du står foran' },
  { id:'denmark_fan',      label:'Danmark Fan',   icon:'🇩🇰', category:'props',    description:'Dansk flag-fodbold malet på begge kinder' },
  // Distortion (image warps)
  { id:'big_mouth',       label:'Stor Mund',    icon:'👄', category:'distortion', description:'Munden forstørres kraftigt' },
  { id:'huge_mouth',      label:'Ekstra Stor Mund', icon:'😮', category:'distortion', description:'Munden forstørres ekstremt (75% mere end Stor Mund)' },
  { id:'big_lips_small',  label:'Store Læber',  icon:'💋', category:'distortion', description:'Læberne forstørres' },
  { id:'big_nose',        label:'Stor Næse',    icon:'👃', category:'distortion', description:'Næsen forstørres kraftigt' },
  { id:'big_ears',        label:'Store Ører',   icon:'👂', category:'distortion', description:'Ørerne forstørres' },
  { id:'big_eyes',        label:'Store Øjne',   icon:'👀', category:'distortion', description:'Forstørrede øjne via billedwarp' },
  { id:'big_eyes_mouth',  label:'Øjne + Mund',  icon:'🤡', category:'distortion', description:'Store øjne og stor mund kombineret' },
  { id:'long_forehead',   label:'Lang Pande',   icon:'🥚', category:'distortion', description:'Panden bliver dobbelt så lang' },
  { id:'alien_head',      label:'Alien Hoved',  icon:'🛸', category:'distortion', description:'Hovedet smalner mod hagen som en alien' },
  { id:'slim_face',       label:'Brede Kinder', icon:'💆', category:'distortion', description:'Midten af ansigtet udvides via pixel-warp' },
  { id:'compress_lower',  label:'Komprimer Nederste', icon:'⬇️', category:'distortion', description:'Nederste del af ansigtet komprimeres' },
  { id:'compress_upper',  label:'Komprimer Øverste',  icon:'⬆️', category:'distortion', description:'Øverste del af ansigtet komprimeres' },
  { id:'swirl_face',      label:'Hvirvel',      icon:'🌀', category:'distortion', description:'Hvirvlende ansigtswarp' },
  { id:'sad_face',        label:'Ked Af Det',   icon:'😢', category:'distortion', description:'Mundvigene trækkes nedad — altid trist' },
  { id:'melt_face',       label:'Smeltet Ansigt', icon:'🫠', category:'distortion', description:'Ansigtet smelter ned med dryppende warp-effekt' },
  // Forvrængning 2
  { id:'micro_nose',      label:'Mikro-næse',     icon:'👃', category:'distortion2', description:'Næsen skrumper til en lillebitte knap' },
  { id:'tiny_eyes',       label:'Små øjne',       icon:'👀', category:'distortion2', description:'Øjnene krymper til små prikker' },
  { id:'bobblehead',      label:'Bobblehead',     icon:'🗿', category:'distortion2', description:'Kæmpe hoved der bobler og svajer' },
  { id:'mini_head',       label:'Mini-hoved',     icon:'🤏', category:'distortion2', description:'Hovedet skrumper til et lille mini-hoved' },
  { id:'jelly_face',      label:'Gelé-ansigt',    icon:'🍮', category:'distortion2', description:'Ansigtet bølger som gelé' },
  { id:'jelly_slowmo',    label:'Slow-mo Gelé',   icon:'🌊', category:'distortion2', description:'Ansigtet skvulper langsomt i tyk gelé' },
  { id:'minecraft_face',  label:'Minecraft',      icon:'🧱', category:'distortion2', description:'Hele ansigtet inkl. issen bliver firkantet som en Minecraft-figur' },
  { id:'triangle_face',   label:'Trekant-ansigt', icon:'🔺', category:'distortion2', description:'Ansigtet trækkes ud i en trekant' },
  { id:'face_explode',    label:'Eksploder',      icon:'💥', category:'distortion2', description:'Ansigtet eksploderer udad og samles igen' },
  { id:'elastic_smile',   label:'Elastik-smil',   icon:'😁', category:'distortion2', description:'Ansigtet strækkes elastisk når du smiler' },
  { id:'jelly_bounce',    label:'Gelé-hop',       icon:'🫨', category:'distortion2', description:'Ansigtet hopper som gelé ved hovedbevægelser' },
  { id:'big_eyes_mini_mouth', label:'Store Øjne + Mini-mund', icon:'😳', category:'distortion2', description:'Kæmpe øjne og en lillebitte mund' },
  { id:'inverse_face',    label:'Omvendt Ansigt', icon:'🙃', category:'distortion2', description:'Stor mund, små øjne og lille næse' },
  { id:'puffy_face',      label:'Buttet Ansigt',  icon:'🐹', category:'distortion2', description:'Oppustet ansigt med runde, fyldige kinder' },
];

export const ALL_FILTERS: FilterDefinition[] = [
  { id:'none', label:'Ingen', icon:'🚫', category:'animal', description:'Intet filter' },
  ...FILTERS,
];
